### ISSUE TITLE
Git Push: HTTPConnectionPool Error: Max Retries reached

### ISSUE THREAD

**Issue by aaronfranco** [tsuru/gandalf#190]
Hello, 

Here is the error I'm getting:

````
remote: text
remote: Traceback (most recent call last):
remote:   File "/usr/local/bin/tsuru_unit_agent", line 9, in <module>
remote:     load_entry_point('tsuru-unit-agent==0.3.10', 'console_scripts', 'tsuru_unit_agent')()
remote:   File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/main.py", line 58, in main
remote:     actions[args.action](args)
remote:   File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/main.py", line 27, in deploy_action
remote:     envs = client.register_unit(args.app_name)
remote:   File "/usr/local/lib/python2.7/dist-packages/tsuru_unit_agent/client.py", line 24, in register_unit
remote:     **params)
remote:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
remote:     return request('post', url, data=data, **kwargs)
remote:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
remote:     return session.request(method=method, url=url, **kwargs)
remote:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
remote:     resp = self.send(prep, **send_kwargs)
remote:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
remote:     r = adapter.send(request, **kwargs)
remote:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
remote:     raise ConnectionError(e)
remote: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8883): Max retries exceeded with url: /apps/nimblesails/units/register (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
remote: Exit status 1
````
Here is my Tsuru Config
````
debug: true
host: http://localhost:8883
admin-team: admin
auth:
    user-registration: true
    scheme: native
database:
    url: 127.0.0.1:27017
    name: tsurudb
pubsub:
    redis-host: 127.0.0.1
    redis-port: 6379
queue:
    mongo-url: 127.0.0.1:27017
    mongo-database: queuedb
git:
    api-server: http://localhost:8000
provisioner: docker
docker:
segregate: false
    router: hipache
    collection: docker_containers
    repository-namespace: tsuru
    deploy-cmd: /var/lib/tsuru/deploy
    cluster:
        storage: mongodb
        mongo-url: 127.0.0.1:27017
        mongo-database: cluster
    run-cmd:
        bin: /var/lib/tsuru/start
        port: "8888"
    ssh:
        add-key-cmd: /var/lib/tsuru/add-key
        user: ubuntu
#    servers:
#        - http://localhost:2375
routers:
    hipache:
        type: hipache
        domain: 127.0.0.1.xip.io
````

I have a feeling there is an issue with my config. I spent time getting Gandalf set up properly, which is why I think my issue might be in my tsuru config. 

Please let me know if you spot anything out of place :+1: 

Also, I can see the basic Tsuru landing page when I visit http://localhost:8883.

**Comment by aaronfranco** [comment]
I also found these errors in my syslog:

````
May 13 23:29:17 INTERCEPTORdell tsr[11368]: Error recovered on flushing writer: "invalid memory address or nil pointer dereference"
May 13 23:29:17 INTERCEPTORdell tsr[11368]: Error writing keepalive, exiting loop: Error recovered on flushing writer: "invalid memory address or nil pointer dereference"
````

**Comment by fsouza** [comment]
Hi @aaronfranco, thanks for reporting this issue. The problem is indeed in the configuration, the value of the "host" entry cannot be localhost, it must be some address that can be seen by the containers that will run the code (for example, 192.168.50.4).

Even if Docker and tsuru are in the same machine, you cannot use localhost, because containers run in a different network, where localhost will mean the container itself. Changing it to the IP address of the server running tsuru should fix it (so, if you're running tsuru in the server 192.168.50.4, the value should be http://192.168.50.4:8883, please ensure that the value of the "listen" entry is "0.0.0.0:8883" as well).

The following config should do the trick (replace "192.168.50.4" with your IP, both in the "host" and "routers:hipache:domain"):

```
debug: true
listen: 0.0.0.0:8883
host: http://192.168.50.4:8883
admin-team: admin
auth:
    user-registration: true
    scheme: native
database:
    url: 127.0.0.1:27017
    name: tsurudb
pubsub:
    redis-host: 127.0.0.1
    redis-port: 6379
queue:
    mongo-url: 127.0.0.1:27017
    mongo-database: queuedb
git:
    api-server: http://localhost:8000
provisioner: docker
docker:
segregate: false
    router: hipache
    collection: docker_containers
    repository-namespace: tsuru
    deploy-cmd: /var/lib/tsuru/deploy
    cluster:
        storage: mongodb
        mongo-url: 127.0.0.1:27017
        mongo-database: cluster
    run-cmd:
        bin: /var/lib/tsuru/start
        port: "8888"
    ssh:
        add-key-cmd: /var/lib/tsuru/add-key
        user: ubuntu
#    servers:
#        - http://localhost:2375
routers:
    hipache:
        type: hipache
        domain: 192.168.50.4.xip.io
```

**Comment by aaronfranco** [comment]
@fsouza Thanks for the fast reply! I made the changes but continue to get the error. However, now my syslog reads differently.

````
May 13 23:42:54 INTERCEPTORdell gandalf-listener[12285]: Executing git-receive-pack /var/lib/gandalf/repositories/nimblesails.git
May 13 23:42:55 INTERCEPTORdell tsr[12230]: [pipeline] running the Forward for the insert-empty-container action
May 13 23:42:55 INTERCEPTORdell tsr[12230]: [pipeline] running the Forward for the create-container action
May 13 23:42:55 INTERCEPTORdell tsr[12230]: create container for app nimblesails, based on image tsuru/nodejs:latest, with cmds [/bin/bash -lc tsuru_unit_agent http://localhost:8883 bd6e4929ef556ceb5575bbe5c16495e15cd1347e nimblesails "/var/lib/tsuru/deploy archive http://192.168.0.25:3232/?id=7115252d94c4ed0191ac1edc0061c205c908da40077d8dec8529f7934b4ee9ea0de290d95e049c3c5cdf3b1916511d781def41cdac7a27d524121a04f72d30fc" deploy]
May 13 23:42:56 INTERCEPTORdell tsr[12230]: [pipeline] running the Forward for the start-container action
May 13 23:42:56 INTERCEPTORdell tsr[12230]: starting container 2eecf827eb4524625b993a6ad1fa8380cbdc57089367afb8b8a55daf52a8377e
May 13 23:42:56 INTERCEPTORdell tsr[12230]: [pipeline] running the Forward for the update-database-container action
May 13 23:42:56 INTERCEPTORdell tsr[12230]: [pipeline] running the Forward for the follow-logs-and-commit action
May 13 23:42:56 INTERCEPTORdell kernel: [ 5091.618497] docker0: port 1(vethc3014ce) entered disabled state
````

**Comment by fsouza** [comment]
@aaronfranco is it the same error?

**Comment by aaronfranco** [comment]
@fsouza Yes, I'm getting the same error when I run Git Push.

**Comment by fsouza** [comment]
Ah, I'm sorry. You also need to recreate the app. There's an issue to sync the host when it's updated (tsuru/tsuru#1195), but currently you need to create another app to update the host it will use.

**Comment by aaronfranco** [comment]
@fsouza Problem Solved!

**Comment by fsouza** [comment]
Cool! Is your application working fine now?

**Comment by aaronfranco** [comment]
Tsuru seems to be fine, however now I'm having NPM issues on install.

**Comment by aaronfranco** [comment]
I tested another app and Tsuru works fine. The app runs without issues.

**Comment by fsouza** [comment]
Cool, thank you!
