### ISSUE TITLE
master (pre-receive hook declined)

### ISSUE THREAD

**Issue by vmalaga** [tsuru/gandalf#199]
Hi.

I have a problem with our tsuru because after the last upgrade I can't make git push any reject the pre-recive hook

```
root@tsurudev:~/teststatic# git push tsusu master 
Counting objects: 3, done.
Writing objects: 100% (3/3), 227 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Traceback (most recent call last):
remote:   File "<stdin>", line 2, in <module>
remote:   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
remote:     return _default_decoder.decode(s)
remote:   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
remote:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
remote:   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
remote:     raise ValueError("No JSON object could be decoded")
remote: ValueError: No JSON object could be decoded
To git@tsurudev.qdqmedia.com:teststatic.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@tsurudev.qdqmedia.com:teststatic.git'
```
I don't know if is gandalf-server or archive-server causing the error.

The gandalf server create the repository on git@tsurudev.qdqmedia.com:teststatic.git but it is empty if i try to clone it
```
root@tsurudev:/tmp# git clone git@tsurudev.qdqmedia.com:teststatic.git
Cloning into 'teststatic'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
```
Is there any way to debug this problem ?

**Comment by vmalaga** [comment]
enabling -x on pre-receive hook I can see the reason of the error, archive-server return missing archive file to the curl request

```
remote: + export TSURU_HOST=http://172.16.70.100:8080
remote: + TSURU_HOST=http://172.16.70.100:8080
remote: + export TSURU_TOKEN=bf1181bb84ef7fe24c8f035cf3941b3843450580
remote: + TSURU_TOKEN=bf1181bb84ef7fe24c8f035cf3941b3843450580
remote: + export ARCHIVE_SERVER_READ=http://172.16.70.100:3232 ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131
remote: + ARCHIVE_SERVER_READ=http://172.16.70.100:3232
remote: + ARCHIVE_SERVER_WRITE=http://127.0.0.1:3131
remote: + read oldrev newrev refname
remote: + set +e
remote: + echo refs/heads/master
remote: + grep -v 'tags/master$'
remote: + grep -q '/master$'
remote: + status=0
remote: + set -e
remote: + '[' 0 = 0 ']'
remote: + COMMIT=1d4cbcf5f55b4720091384241ce163155f3d1607
remote: + read oldrev newrev refname
remote: + '[' -z 1d4cbcf5f55b4720091384241ce163155f3d1607 ']'
remote: + APP_DIR=tests3.git
remote: + APP_NAME=tests3
remote: ++ generate_archive /var/lib/gandalf/repositories/tests3.git 1d4cbcf5f55b4720091384241ce163155f3d1607
remote: ++ url=http://127.0.0.1:3131/
remote: +++ curl -sNd 'path=/var/lib/gandalf/repositories/tests3.git&refid=1d4cbcf5f55b4720091384241ce163155f3d1607' http://127.0.0.1:3131/
remote: ++ result='missing archive file'
```

**Comment by fsouza** [comment]
@vmalaga looks like it's indeed archive-server. Did you upgrade it as well? If so, could you please upgrade the pre-receive hook? There was a change in the archive-server (I expected it to be backward compatible, but looks like it wasn't).

I'm at the moment fixing archive-server so it's backward compatible, sorry for about that :-(

**Comment by fsouza** [comment]
Launchpad is finishing the build of the deb packages, can you try upgrading archive-server afterwards and confirm that it works as expected?

**Comment by vmalaga** [comment]
@fsouza I just upgraded archive-server and now it works like expected.  Thanks for the speed, so leave the platform working for tomorrow.

I am going to finish review all the stack to give the upgrade to 0.13 closed

**Comment by fsouza** [comment]
@vmalaga awesome, please let us know if you find any other issue.
